# Generated by Django 6.0.3 on 2026-03-19 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_story_comment_storyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('BEAUTY', 'Красота и уход'), ('HEALTH', 'Здоровье'), ('REALTY', 'Недвижимость'), ('EDUCATION', 'Образование'), ('FINANCE', 'Финансы'), ('LEGAL', 'Юридические услуги'), ('TOURISM', 'Туризм'), ('FOOD', 'Еда и рестораны'), ('TRANSPORT', 'Транспорт'), ('OTHER', 'Другое')], default='OTHER', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_vip', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('owner', models.OneToOneField(limit_choices_to={'role': 'BUSINESS'}, on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
                'ordering': ['-is_vip', '-rating', '-created_at'],
            },
        ),
    ]
