# Generated by Django 6.0.3 on 2026-03-19 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_verificationrequest_verificationmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='media_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='stories/'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(choices=[('TRY', '₺ Лира'), ('USD', '$ Доллар'), ('EUR', '€ Евро'), ('RUB', '₽ Рубль')], default='TRY', max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image_url', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Shop.business')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
    ]
