# Generated by Django 6.0.2 on 2026-05-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_productinquiry_business_alter_article_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
