# Generated by Django 6.0.2 on 2026-05-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_business_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Complaint reason',
                'verbose_name_plural': 'Complaint reasons',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reason',
            field=models.CharField(blank=True, default='OTHER', max_length=120),
        ),
    ]
