# Generated by Django 6.0.2 on 2026-05-16 10:50

from django.db import migrations


DEFAULT_REASONS = [
    'Спам',
    'Неприемлемый контент',
    'Мошенничество',
    'Дезинформация',
    'Другое',
]


def seed_reasons(apps, schema_editor):
    ComplaintReason = apps.get_model('Shop', 'ComplaintReason')
    if ComplaintReason.objects.exists():
        return
    for i, label in enumerate(DEFAULT_REASONS):
        ComplaintReason.objects.create(label=label, order=i, is_active=True)


def unseed_reasons(apps, schema_editor):
    ComplaintReason = apps.get_model('Shop', 'ComplaintReason')
    ComplaintReason.objects.filter(label__in=DEFAULT_REASONS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_complaintreason_alter_complaint_reason'),
    ]

    operations = [
        migrations.RunPython(seed_reasons, unseed_reasons),
    ]
