# Generated by Django 6.0.2 on 2026-05-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_seed_complaint_reasons'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(max_length=6)),
                ('code_type', models.CharField(choices=[('REGISTRATION', 'Registration'), ('PASSWORD_RESET', 'Password Reset')], default='REGISTRATION', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Email Verification Code',
                'verbose_name_plural': 'Email Verification Codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'code'], name='Shop_emailv_email_fb8eb7_idx'), models.Index(fields=['code_type', 'is_used'], name='Shop_emailv_code_ty_9e3018_idx')],
            },
        ),
    ]
