# Generated by Django 6.0.2 on 2026-03-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_group_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='can_delete_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_pin_messages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='can_send_messages',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Владелец'), ('ADMIN', 'Администратор'), ('MODERATOR', 'Модератор'), ('MEMBER', 'Участник')], default='MEMBER', max_length=10),
        ),
    ]
