# Generated by Django 6.0.2 on 2026-03-21 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_add_moderator_role_and_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='Shop.groupchat'),
        ),
    ]
