# Generated by Django 6.0.2 on 2026-03-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_business_group_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inquirymessage',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
