# Generated by Django 6.0.2 on 2026-05-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_survey_surveyoption_surveyresponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyoption',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='surveyresponse',
            name='is_correct',
        ),
    ]
