# Generated by Django 6.0.3 on 2026-05-30 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0013_business_card_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='Shop.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_businesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Business Favorite',
                'verbose_name_plural': 'Business Favorites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'business')},
            },
        ),
    ]
