# Generated by Django 6.0.2 on 2026-06-03 06:30

from django.db import migrations, models
from django.db.models import Q


def mark_existing_text_posts_as_tweets(apps, schema_editor):
    """До этой миграции «твит» = пост без медиа (создать его мог только Pro/VIP).
    Чтобы старые твиты не пропали из вкладки «Твиты», помечаем все существующие
    посты без media и media_url как is_tweet=True. Посты с медиа остаются постами."""
    Post = apps.get_model('Shop', 'Post')
    no_media = (Q(media='') | Q(media__isnull=True)) & (Q(media_url='') | Q(media_url__isnull=True))
    Post.objects.filter(no_media).update(is_tweet=True)


def unmark(apps, schema_editor):
    Post = apps.get_model('Shop', 'Post')
    Post.objects.update(is_tweet=False)


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0015_newsfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_tweet',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_text_posts_as_tweets, unmark),
    ]
