# Generated by Django 6.0.2 on 2026-06-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0016_post_is_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='block_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='post',
            name='block_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='block_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='review',
            name='block_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='story',
            name='block_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('FOLLOW', 'Новый подписчик'), ('NEW_POST', 'Новый пост'), ('INQUIRY_MSG', 'Сообщение в запросе'), ('GROUP_MSG', 'Сообщение в группе'), ('CONTENT_BLOCKED', 'Контент заблокирован'), ('PROFILE_BLOCKED', 'Профиль заблокирован')], max_length=30),
        ),
    ]
