# Generated by Django 6.0.2 on 2026-06-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0017_comment_block_reason_post_block_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media_format',
            field=models.CharField(blank=True, choices=[('4:5', 'Вертикальное 4:5'), ('2:3', 'Книжное 2:3'), ('1:1', 'Квадрат 1:1'), ('16:9', 'Горизонтальное 16:9')], default='4:5', max_length=8),
        ),
    ]
